name = "navy-fortress-api"
main = "src/worker.js"
compatibility_date = "2024-02-12"

# Database
[[d1_databases]]
binding = "DB"
database_name = "usn_db"
database_id = "d879044b-dba8-4b50-b7be-55b0fb4755d0"

# Environment variables
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-secret-here"

[build]
command = "npm run build"
watch_dir = "src"

[env.production]
vars = { ENVIRONMENT = "production" }